plugins {
    alias(libs.plugins.android.application)
}

android {

    namespace 'app.aira.viscount'
    compileSdk rootProject.ext.compileSdkVersion
    ndkVersion = "29.0.13846066"
    defaultConfig {
        applicationId "app.aira.viscount"
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        splits {
            abi {
                enable true
                reset()
                
                include 'armeabi-v7a', "arm64-v8a"
                universalApk true
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    packaging {
        jniLibs {
            excludes.add("**/libandroidx.graphics.path.so")
        }
        resources {
            excludes.add("**/libandroidx.graphics.path.so")
        }
    }
    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            output.outputFileName = "ViscountLoader_${variant.versionName}_${output.baseName}.apk"
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
    implementation project(':Bcore')

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
